# background, long-lived TCP streams
# 10 flows aiming at an aggregate bitrate of 10Mbps
# TODO set LEDBAT as CC

label: &l tcp-scavenger

port: &p 5002

instances: &i 10

client:
  at:
    - 0s
  config:
    server-address: iperf-server
    server-port: *p
    time-s: 60
    title: *l
    # mss: 1400
    # report-interval-s: 0.2
    parallel: *i
    target-bitrate: 1M
    reverse: true

server:
  at:
    - 0s
  config:
    server-port: *p
