version: '3'

services:
  iperf-client:
    privileged: true
    build:
      context: image
    entrypoint: /root/entrypoint.bash "client"
    container_name: iperf-client
    networks:
      traffic:
      measure:
    volumes:
      - ./etc:/root/share
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  iperf-server:
    privileged: true
    build:
      context: image
    entrypoint: /root/entrypoint.bash "server"
    container_name: iperf-server
    networks:
      traffic:
      # iperf servers won't send stats
    volumes:
      - ./etc:/root/share
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  influxdb:
    image: influxdb:1.3.5
    container_name: influxdb
    networks:
      measure:
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      measure:
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource

networks:
  traffic:
  measure:

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
