# starts at 2 for 1s, sleeps 3s and go again
# 3 instances, doing a ~1.2M transfer (the average Alexa top-1000 page size)

label: &l tcp-short-b

port: &p 5006

instances: &i 3

client:
  at:
    - 2s
    - 6s
    - 10s
    - 14s
    - 18s
    - 22s
    - 26s
    - 30s
    - 34s
    - 38s
    - 42s
    - 46s
    - 50s
    - 54s
    - 58s

  config:
    server-address: iperf-server.docker_traffic
    server-port: *p
    title: *l
    bytes: 1246K
    mss: 1400
    report-interval-s: 0.2
    parallel: *i

server:
  at:
    - 0s
  config:
    server-port: *p
