label: &l tcp-greedy-2

port: &p 5002

client:
  at:
    - 0s
  config:
    server-address: iperf-server
    server-port: *p
    time-s: 60
    title: *l
    report-interval-s: 0.2

server:
  at:
    - 0s
  config:
    server-port: *p
