label: &l rt_audio

port: &p 5001

client:
  at:
    - 0s
  config:
    server-address: iperf-server
    server-port: *p
    time-s: 60
    udp: true
    length: 126
    target-bitrate: 63901
    title: *l
    report-interval-s: 0.2

server:
  at:
    - 0s
  config:
    server-port: *p
