# models one direction of a real-time video stream (e.g., skype) (810Kbps, 930 bytes of RTP & media)
# ToS field explicitly bleached
label: &l REF-rt_video

port: &p 10003
mark: &m 0x00

client:
  at:
    - 0s
  config:
    server-address: iperf-server
    server-port: *p
    time-s: 60
    udp: true
    length: 930
    target-bitrate: 810K
    tos: *m
    title: *l
    reverse: true
    # report-interval-s: 0.2

server:
  at:
    - 0s
  config:
    server-port: *p
