


label: &l abr-video

port: &p 5402

client:
  at:
    - 9s

    - 19s

    - 29s

    - 39s

    - 49s

    - 59s

  config:
    server-address: iperf-server
    server-port: *p
    title: *l
    bytes: 1.8M
    reverse: true
    report-interval-s: 0.200000

server:
  at:
    - 0s
  config:
    server-port: *p
