


label: &l web-page

port: &p 5504

client:
  at:
    - 4s

    - 14s

    - 24s

    - 34s

    - 44s

    - 54s

  config:
    server-address: iperf-server
    server-port: *p
    title: *l
    bytes: 1246K
    reverse: true
    report-interval-s: 0.200000

server:
  at:
    - 0s
  config:
    server-port: *p
