# try to transfer 75MB with 3 TCP flows
# enters after 15s, i.e. in an already busy network

label: &l tcp-high-throughput

port: &p 5000

# instances: &i 3

client:
  at:
    - 15s
    - 30s
    - 45s
  config:
    server-address: iperf-server
    server-port: *p
    # time-s: 60
    title: *l
    # mss: 1400
    # report-interval-s: 0.2
    # parallel: *i
    # target-bitrate: 10M
    # fq-rate: 10M
    bytes: 25M

server:
  at:
    - 0s
  config:
    server-port: *p
